"""BigQuery table schemas for different providers.

Contains table configurations and schema definitions for uploading
provider data to BigQuery.
"""

from dataclasses import dataclass
from typing import Any

from google.cloud.bigquery import SchemaField


@dataclass
class TableConfig:
    """Configuration for a BigQuery table."""
    name: str
    schema: list[SchemaField]
    source_pattern: str  # glob pattern for source files
    merge_files: bool = False  # whether to merge multiple files into one table


def _make_schema(*fields: tuple[str, str, str]) -> list[SchemaField]:
    """Helper to build schema from (name, type, mode) tuples."""
    return [SchemaField(name, field_type, mode=mode) for name, field_type, mode in fields]


# Schema definitions for Garmin data
GARMIN_SCHEMAS: dict[str, TableConfig] = {
    "activities": TableConfig(
        name="activities",
        schema=_make_schema(
            ("activityId", "INTEGER", "REQUIRED"),
            ("activityName", "STRING", "NULLABLE"),
            ("startTimeLocal", "STRING", "NULLABLE"),
            ("startTimeGMT", "STRING", "NULLABLE"),
            ("endTimeGMT", "STRING", "NULLABLE"),
            ("activityType", "JSON", "NULLABLE"),
            ("eventType", "JSON", "NULLABLE"),
            ("distance", "FLOAT", "NULLABLE"),
            ("duration", "FLOAT", "NULLABLE"),
            ("elapsedDuration", "FLOAT", "NULLABLE"),
            ("movingDuration", "FLOAT", "NULLABLE"),
            ("elevationGain", "FLOAT", "NULLABLE"),
            ("elevationLoss", "FLOAT", "NULLABLE"),
            ("elevationCorrected", "BOOLEAN", "NULLABLE"),
            ("averageSpeed", "FLOAT", "NULLABLE"),
            ("maxSpeed", "FLOAT", "NULLABLE"),
            ("startLatitude", "FLOAT", "NULLABLE"),
            ("startLongitude", "FLOAT", "NULLABLE"),
            ("endLatitude", "FLOAT", "NULLABLE"),
            ("endLongitude", "FLOAT", "NULLABLE"),
            ("calories", "FLOAT", "NULLABLE"),
            ("bmrCalories", "FLOAT", "NULLABLE"),
            ("autoCalcCalories", "BOOLEAN", "NULLABLE"),
            ("averageHR", "FLOAT", "NULLABLE"),
            ("maxHR", "FLOAT", "NULLABLE"),
            ("averageRunningCadenceInStepsPerMinute", "FLOAT", "NULLABLE"),
            ("maxRunningCadenceInStepsPerMinute", "FLOAT", "NULLABLE"),
            ("averageSwimCadenceInStrokesPerMinute", "FLOAT", "NULLABLE"),
            ("maxSwimCadenceInStrokesPerMinute", "FLOAT", "NULLABLE"),
            ("averageSwolf", "FLOAT", "NULLABLE"),
            ("avgStrokeDistance", "FLOAT", "NULLABLE"),
            ("avgStrokes", "FLOAT", "NULLABLE"),
            ("strokes", "FLOAT", "NULLABLE"),
            ("activeLengths", "FLOAT", "NULLABLE"),
            ("poolLength", "FLOAT", "NULLABLE"),
            ("unitOfPoolLength", "JSON", "NULLABLE"),
            ("maxDoubleCadence", "FLOAT", "NULLABLE"),
            ("avgStrideLength", "FLOAT", "NULLABLE"),
            ("steps", "INTEGER", "NULLABLE"),
            ("ownerId", "INTEGER", "NULLABLE"),
            ("ownerDisplayName", "STRING", "NULLABLE"),
            ("ownerFullName", "STRING", "NULLABLE"),
            ("ownerProfileImageUrlSmall", "STRING", "NULLABLE"),
            ("ownerProfileImageUrlMedium", "STRING", "NULLABLE"),
            ("ownerProfileImageUrlLarge", "STRING", "NULLABLE"),
            ("deviceId", "INTEGER", "NULLABLE"),
            ("manufacturer", "STRING", "NULLABLE"),
            ("locationName", "STRING", "NULLABLE"),
            ("lapCount", "INTEGER", "NULLABLE"),
            ("sportTypeId", "INTEGER", "NULLABLE"),
            ("aerobicTrainingEffect", "FLOAT", "NULLABLE"),
            ("aerobicTrainingEffectMessage", "STRING", "NULLABLE"),
            ("anaerobicTrainingEffect", "FLOAT", "NULLABLE"),
            ("anaerobicTrainingEffectMessage", "STRING", "NULLABLE"),
            ("vO2MaxValue", "FLOAT", "NULLABLE"),
            ("trainingEffectLabel", "STRING", "NULLABLE"),
            ("activityTrainingLoad", "FLOAT", "NULLABLE"),
            ("beginTimestamp", "INTEGER", "NULLABLE"),
            ("timeZoneId", "INTEGER", "NULLABLE"),
            ("minElevation", "FLOAT", "NULLABLE"),
            ("maxElevation", "FLOAT", "NULLABLE"),
            ("maxVerticalSpeed", "FLOAT", "NULLABLE"),
            ("maxTemperature", "FLOAT", "NULLABLE"),
            ("minTemperature", "FLOAT", "NULLABLE"),
            ("moderateIntensityMinutes", "FLOAT", "NULLABLE"),
            ("vigorousIntensityMinutes", "FLOAT", "NULLABLE"),
            ("fastestSplit_100", "FLOAT", "NULLABLE"),
            ("fastestSplit_400", "FLOAT", "NULLABLE"),
            ("fastestSplit_750", "FLOAT", "NULLABLE"),
            ("fastestSplit_1000", "FLOAT", "NULLABLE"),
            ("minActivityLapDuration", "FLOAT", "NULLABLE"),
            ("waterEstimated", "FLOAT", "NULLABLE"),
            ("differenceBodyBattery", "FLOAT", "NULLABLE"),
            ("hasPolyline", "BOOLEAN", "NULLABLE"),
            ("hasImages", "BOOLEAN", "NULLABLE"),
            ("hasVideo", "BOOLEAN", "NULLABLE"),
            ("hasHeatMap", "BOOLEAN", "NULLABLE"),
            ("hasSplits", "BOOLEAN", "NULLABLE"),
            ("favorite", "BOOLEAN", "NULLABLE"),
            ("manualActivity", "BOOLEAN", "NULLABLE"),
            ("userPro", "BOOLEAN", "NULLABLE"),
            ("purposeful", "BOOLEAN", "NULLABLE"),
            ("qualifyingDive", "BOOLEAN", "NULLABLE"),
            ("decoDive", "BOOLEAN", "NULLABLE"),
            ("atpActivity", "BOOLEAN", "NULLABLE"),
            ("hrTimeInZone_1", "FLOAT", "NULLABLE"),
            ("hrTimeInZone_2", "FLOAT", "NULLABLE"),
            ("hrTimeInZone_3", "FLOAT", "NULLABLE"),
            ("hrTimeInZone_4", "FLOAT", "NULLABLE"),
            ("hrTimeInZone_5", "FLOAT", "NULLABLE"),
            ("privacy", "JSON", "NULLABLE"),
            ("userRoles", "JSON", "NULLABLE"),
            ("summarizedDiveInfo", "JSON", "NULLABLE"),
            ("splitSummaries", "JSON", "NULLABLE"),
            ("parent", "JSON", "NULLABLE"),
            ("pr", "JSON", "NULLABLE"),
        ),
        source_pattern="all_activities.json",
        merge_files=False,
    ),
    "activity_details": TableConfig(
        name="activity_details",
        schema=_make_schema(
            ("activityId", "INTEGER", "REQUIRED"),
            ("measurementCount", "INTEGER", "NULLABLE"),
            ("metricsCount", "INTEGER", "NULLABLE"),
            ("totalMetricsCount", "INTEGER", "NULLABLE"),
            ("detailsAvailable", "BOOLEAN", "NULLABLE"),
            ("pendingData", "BOOLEAN", "NULLABLE"),
            ("metricDescriptors", "JSON", "NULLABLE"),
            ("activityDetailMetrics", "JSON", "NULLABLE"),
            ("geoPolylineDTO", "JSON", "NULLABLE"),
            ("heartRateDTOs", "JSON", "NULLABLE"),
        ),
        source_pattern="activity_*_details.json",
        merge_files=True,
    ),
    "devices": TableConfig(
        name="devices",
        schema=_make_schema(
            ("deviceTypePk", "INTEGER", "NULLABLE"),
            ("deviceId", "INTEGER", "NULLABLE"),
            ("applicationKey", "STRING", "NULLABLE"),
            ("productDisplayName", "STRING", "NULLABLE"),
            ("productSku", "STRING", "NULLABLE"),
            ("actualProductSku", "STRING", "NULLABLE"),
            ("partNumber", "STRING", "NULLABLE"),
            ("imageUrl", "STRING", "NULLABLE"),
            ("shortName", "STRING", "NULLABLE"),
            ("displayName", "STRING", "NULLABLE"),
            ("serialNumber", "STRING", "NULLABLE"),
            ("unitId", "STRING", "NULLABLE"),
            ("currentFirmwareVersion", "STRING", "NULLABLE"),
            ("currentFirmwareVersionMajor", "INTEGER", "NULLABLE"),
            ("currentFirmwareVersionMinor", "INTEGER", "NULLABLE"),
            ("displayOrder", "INTEGER", "NULLABLE"),
            ("golfDisplayOrder", "INTEGER", "NULLABLE"),
            ("registeredDate", "STRING", "NULLABLE"),
            ("deviceStatus", "STRING", "NULLABLE"),
            ("datasource", "STRING", "NULLABLE"),
            ("deviceSettingsFile", "STRING", "NULLABLE"),
            ("gcmSettingsFile", "STRING", "NULLABLE"),
            ("deviceTypeSimpleName", "STRING", "NULLABLE"),
            ("primary", "BOOLEAN", "NULLABLE"),
            ("activeInd", "BOOLEAN", "NULLABLE"),
            ("wifi", "BOOLEAN", "NULLABLE"),
            ("wifiSetup", "BOOLEAN", "NULLABLE"),
            ("hasOpticalHeartRate", "BOOLEAN", "NULLABLE"),
            ("appSupport", "BOOLEAN", "NULLABLE"),
            ("bluetoothClassicDevice", "BOOLEAN", "NULLABLE"),
            ("bluetoothLowEnergyDevice", "BOOLEAN", "NULLABLE"),
            ("cellularCapable", "BOOLEAN", "NULLABLE"),
            ("nfcCapable", "BOOLEAN", "NULLABLE"),
            ("solarChargeCapable", "BOOLEAN", "NULLABLE"),
            ("highlighted", "BOOLEAN", "NULLABLE"),
            ("hybrid", "BOOLEAN", "NULLABLE"),
            ("wellness", "BOOLEAN", "NULLABLE"),
            ("weightScale", "BOOLEAN", "NULLABLE"),
            ("corporateDevice", "BOOLEAN", "NULLABLE"),
            ("unRetirable", "BOOLEAN", "NULLABLE"),
            ("isPrimaryUser", "BOOLEAN", "NULLABLE"),
            ("prePairedWithHRM", "BOOLEAN", "NULLABLE"),
            ("hasPowerButton", "BOOLEAN", "NULLABLE"),
            ("vivohubCompatible", "BOOLEAN", "NULLABLE"),
            ("vivohubConfigurable", "BOOLEAN", "NULLABLE"),
            ("supportsSecondaryUsers", "BOOLEAN", "NULLABLE"),
            ("wasp", "BOOLEAN", "NULLABLE"),
            ("abnormalHeartRateAlertCapable", "BOOLEAN", "NULLABLE"),
            ("accessorySensorCanGenerateActivityCapable", "BOOLEAN", "NULLABLE"),
            ("activitySummFitFileCapable", "BOOLEAN", "NULLABLE"),
            ("actualStepRecordingCapable", "BOOLEAN", "NULLABLE"),
            ("acuteChronicWorkloadRatioCapable", "BOOLEAN", "NULLABLE"),
            ("acuteTrainingLoadCapable", "BOOLEAN", "NULLABLE"),
            ("adaptiveCoachingFitnessCapable", "BOOLEAN", "NULLABLE"),
            ("adaptiveCoachingNoviceCapable", "BOOLEAN", "NULLABLE"),
            ("adaptiveCoachingScheduleCapable", "BOOLEAN", "NULLABLE"),
            ("adaptiveCoachingStrengthCapable", "BOOLEAN", "NULLABLE"),
            ("adaptiveCoachingStrengthReceiveCapable", "BOOLEAN", "NULLABLE"),
            ("adaptiveCoachingWalkCapable", "BOOLEAN", "NULLABLE"),
            ("adaptiveCoachingWorkoutSettingsCapable", "BOOLEAN", "NULLABLE"),
            ("aerobicTrainingEffectCapable", "BOOLEAN", "NULLABLE"),
            ("airIntegrationCapable", "BOOLEAN", "NULLABLE"),
            ("alarmDaysCapable", "BOOLEAN", "NULLABLE"),
            ("allDayStressCapable", "BOOLEAN", "NULLABLE"),
            ("altitudeAcclimationPercentageCapable", "BOOLEAN", "NULLABLE"),
            ("anaerobicTrainingEffectCapable", "BOOLEAN", "NULLABLE"),
            ("archeryXCapable", "BOOLEAN", "NULLABLE"),
            ("assistancePlusCapable", "BOOLEAN", "NULLABLE"),
            ("atpWorkoutCapable", "BOOLEAN", "NULLABLE"),
            ("batteryStatusCapable", "BOOLEAN", "NULLABLE"),
            ("bbiRecordingCapable", "BOOLEAN", "NULLABLE"),
            ("beaconTrackingCapable", "BOOLEAN", "NULLABLE"),
            ("benchmarkExerciseCapable", "BOOLEAN", "NULLABLE"),
            ("bloodPressureCapable", "BOOLEAN", "NULLABLE"),
            ("bodyBatteryCapable", "BOOLEAN", "NULLABLE"),
            ("bodyBatteryTrueUpCapable", "BOOLEAN", "NULLABLE"),
            ("breathingDisruptionsCapable", "BOOLEAN", "NULLABLE"),
            ("brickWorkoutCapable", "BOOLEAN", "NULLABLE"),
            ("cardioCapable", "BOOLEAN", "NULLABLE"),
            ("cardioOptionCapable", "BOOLEAN", "NULLABLE"),
            ("cardioSportsCapable", "BOOLEAN", "NULLABLE"),
            ("cardioWorkoutCapable", "BOOLEAN", "NULLABLE"),
            ("changeLogCapable", "BOOLEAN", "NULLABLE"),
            ("collapsibleControlMenuCapable", "BOOLEAN", "NULLABLE"),
            ("connectedGPSCapable", "BOOLEAN", "NULLABLE"),
            ("contactManagementCapable", "BOOLEAN", "NULLABLE"),
            ("courseCapable", "BOOLEAN", "NULLABLE"),
            ("coursePlannerCapable", "BOOLEAN", "NULLABLE"),
            ("coursePromptCapable", "BOOLEAN", "NULLABLE"),
            ("criticalSwimSpeedCapable", "BOOLEAN", "NULLABLE"),
            ("customIntensityMinutesCapable", "BOOLEAN", "NULLABLE"),
            ("customWorkoutCapable", "BOOLEAN", "NULLABLE"),
            ("cyclingAbilityCapable", "BOOLEAN", "NULLABLE"),
            ("cyclingComputerBackupRestoreCapable", "BOOLEAN", "NULLABLE"),
            ("cyclingHeartRateZoneCapable", "BOOLEAN", "NULLABLE"),
            ("cyclingPowerZonesCapable", "BOOLEAN", "NULLABLE"),
            ("cyclingSegmentCapable", "BOOLEAN", "NULLABLE"),
            ("cyclingSportsCapable", "BOOLEAN", "NULLABLE"),
            ("cyclingWorkoutCapable", "BOOLEAN", "NULLABLE"),
            ("dayOfWeekSleepWindowCapable", "BOOLEAN", "NULLABLE"),
            ("defaultHeartRateZoneCapable", "BOOLEAN", "NULLABLE"),
            ("defaultSettingCapable", "BOOLEAN", "NULLABLE"),
            ("descriptiveTrainingEffectCapable", "BOOLEAN", "NULLABLE"),
            ("deviceSettingCapable", "BOOLEAN", "NULLABLE"),
            ("displayFieldsExtCapable", "BOOLEAN", "NULLABLE"),
            ("diveAlertCapable", "BOOLEAN", "NULLABLE"),
            ("diveAppSyncCapable", "BOOLEAN", "NULLABLE"),
            ("divingCapable", "BOOLEAN", "NULLABLE"),
            ("ecgCapable", "BOOLEAN", "NULLABLE"),
            ("ellipticalOptionCapable", "BOOLEAN", "NULLABLE"),
            ("emergencyCallingCapable", "BOOLEAN", "NULLABLE"),
            ("enhancedWorkoutStepCapable", "BOOLEAN", "NULLABLE"),
            ("fitnessAgeV2Capable", "BOOLEAN", "NULLABLE"),
            ("floorsClimbedGoalCapable", "BOOLEAN", "NULLABLE"),
            ("ftpCapable", "BOOLEAN", "NULLABLE"),
            ("fullNameSettingsCapable", "BOOLEAN", "NULLABLE"),
            ("garminEpicsCapable", "BOOLEAN", "NULLABLE"),
            ("garminWellnessCoachCapable", "BOOLEAN", "NULLABLE"),
            ("gcj02CourseCapable", "BOOLEAN", "NULLABLE"),
            ("gearTrackingCapable", "BOOLEAN", "NULLABLE"),
            ("glonassCapable", "BOOLEAN", "NULLABLE"),
            ("goalCapable", "BOOLEAN", "NULLABLE"),
            ("golfAppPairingCapable", "BOOLEAN", "NULLABLE"),
            ("golfAppSyncCapable", "BOOLEAN", "NULLABLE"),
            ("golfCourseDownloadCapable", "BOOLEAN", "NULLABLE"),
            ("golfLiveScoringCapable", "BOOLEAN", "NULLABLE"),
            ("gpsRouteCapable", "BOOLEAN", "NULLABLE"),
            ("groupTrack2Capable", "BOOLEAN", "NULLABLE"),
            ("handednessCapable", "BOOLEAN", "NULLABLE"),
            ("healthSnapshotCapable", "BOOLEAN", "NULLABLE"),
            ("healthStatusCapable", "BOOLEAN", "NULLABLE"),
            ("healthStatusTrueUpCapable", "BOOLEAN", "NULLABLE"),
            ("heatAndAltitudeAcclimationCapable", "BOOLEAN", "NULLABLE"),
            ("hideSoftwareUpdateVersionCapable", "BOOLEAN", "NULLABLE"),
            ("hiitWorkoutCapable", "BOOLEAN", "NULLABLE"),
            ("hillScoreAndEnduranceScoreCapable", "BOOLEAN", "NULLABLE"),
            ("hrvStatusCapable", "BOOLEAN", "NULLABLE"),
            ("hrvStressCapable", "BOOLEAN", "NULLABLE"),
            ("hrZoneCapable", "BOOLEAN", "NULLABLE"),
            ("incidentDetectionCapable", "BOOLEAN", "NULLABLE"),
            ("indoorBikeOptionsCapable", "BOOLEAN", "NULLABLE"),
            ("indoorTrackOptionsCapable", "BOOLEAN", "NULLABLE"),
            ("indoorWalkOptionsCapable", "BOOLEAN", "NULLABLE"),
            ("intensityMinutesGoalCapable", "BOOLEAN", "NULLABLE"),
            ("intensityMinutesV2Capable", "BOOLEAN", "NULLABLE"),
            ("jetlagCapable", "BOOLEAN", "NULLABLE"),
            ("lactateThresholdCapable", "BOOLEAN", "NULLABLE"),
            ("languageSettingCapable", "BOOLEAN", "NULLABLE"),
            ("lapByCoursePointsCapable", "BOOLEAN", "NULLABLE"),
            ("launchMonitorEventSharingCapable", "BOOLEAN", "NULLABLE"),
            ("lhaBackupCapable", "BOOLEAN", "NULLABLE"),
            ("lifestyleLoggingCapable", "BOOLEAN", "NULLABLE"),
            ("liveTrackCapable", "BOOLEAN", "NULLABLE"),
            ("localWindConditionsCapable", "BOOLEAN", "NULLABLE"),
            ("lowHrAlertCapable", "BOOLEAN", "NULLABLE"),
            ("lteLiveEventSharingCapable", "BOOLEAN", "NULLABLE"),
            ("maxHRCapable", "BOOLEAN", "NULLABLE"),
            ("measurementUnitSettingCapable", "BOOLEAN", "NULLABLE"),
            ("metricsFitFileReceiveCapable", "BOOLEAN", "NULLABLE"),
            ("metricsUploadCapable", "BOOLEAN", "NULLABLE"),
            ("militaryTimeCapable", "BOOLEAN", "NULLABLE"),
            ("mobilityWorkoutCapable", "BOOLEAN", "NULLABLE"),
            ("moderateIntensityMinutesGoalCapable", "BOOLEAN", "NULLABLE"),
            ("multipleGolfCourseCapable", "BOOLEAN", "NULLABLE"),
            ("multisportWorkoutCapable", "BOOLEAN", "NULLABLE"),
            ("onDeviceSleepCalculationCapable", "BOOLEAN", "NULLABLE"),
            ("openWaterSwimOptionCapable", "BOOLEAN", "NULLABLE"),
            ("openWaterSwimWorkoutCapable", "BOOLEAN", "NULLABLE"),
            ("otherOptionCapable", "BOOLEAN", "NULLABLE"),
            ("otherSportsCapable", "BOOLEAN", "NULLABLE"),
            ("pacebandCapable", "BOOLEAN", "NULLABLE"),
            ("passcodeLockCapable", "BOOLEAN", "NULLABLE"),
            ("personalRecordCapable", "BOOLEAN", "NULLABLE"),
            ("personalRepRecordCapable", "BOOLEAN", "NULLABLE"),
            ("phoneVerificationCheckRequired", "BOOLEAN", "NULLABLE"),
            ("pilatesWorkoutCapable", "BOOLEAN", "NULLABLE"),
            ("poolSwimOptionCapable", "BOOLEAN", "NULLABLE"),
            ("powerCurveCapable", "BOOLEAN", "NULLABLE"),
            ("powerGuidanceCapable", "BOOLEAN", "NULLABLE"),
            ("powerZonesCapable", "BOOLEAN", "NULLABLE"),
            ("primaryActivityTrackerSettingCapable", "BOOLEAN", "NULLABLE"),
            ("primaryTrainingBackupCapable", "BOOLEAN", "NULLABLE"),
            ("primaryTrainingCapable", "BOOLEAN", "NULLABLE"),
            ("projectedRaceTimePredictionCapable", "BOOLEAN", "NULLABLE"),
            ("publicBetaSoftwareCapable", "BOOLEAN", "NULLABLE"),
            ("pulseOxAllDayCapable", "BOOLEAN", "NULLABLE"),
            ("pulseOxOnDemandCapable", "BOOLEAN", "NULLABLE"),
            ("pulseOxSleepCapable", "BOOLEAN", "NULLABLE"),
            ("racePredictionsRunCapable", "BOOLEAN", "NULLABLE"),
            ("realTimeSettingsCapable", "BOOLEAN", "NULLABLE"),
            ("rechargeableSensorCapable", "BOOLEAN", "NULLABLE"),
            ("registrationMetricsBackfillUnsupported", "BOOLEAN", "NULLABLE"),
            ("remCapable", "BOOLEAN", "NULLABLE"),
            ("reminderAlarmCapable", "BOOLEAN", "NULLABLE"),
            ("reorderablePagesCapable", "BOOLEAN", "NULLABLE"),
            ("requiresInitialDeviceNickname", "BOOLEAN", "NULLABLE"),
            ("respirationCapable", "BOOLEAN", "NULLABLE"),
            ("restingHRCapable", "BOOLEAN", "NULLABLE"),
            ("rideOptionsCapable", "BOOLEAN", "NULLABLE"),
            ("rowingCapable", "BOOLEAN", "NULLABLE"),
            ("rts20Capable", "BOOLEAN", "NULLABLE"),
            ("runningEconomyCapable", "BOOLEAN", "NULLABLE"),
            ("runningHeartRateZoneCapable", "BOOLEAN", "NULLABLE"),
            ("runningLactateThresholdCapable", "BOOLEAN", "NULLABLE"),
            ("runningPowerZonesCapable", "BOOLEAN", "NULLABLE"),
            ("runningSegmentCapable", "BOOLEAN", "NULLABLE"),
            ("runningSportsCapable", "BOOLEAN", "NULLABLE"),
            ("runningToleranceCapable", "BOOLEAN", "NULLABLE"),
            ("runningWorkoutCapable", "BOOLEAN", "NULLABLE"),
            ("runOptionIndoorCapable", "BOOLEAN", "NULLABLE"),
            ("runOptionsCapable", "BOOLEAN", "NULLABLE"),
            ("scheduleCapable", "BOOLEAN", "NULLABLE"),
            ("secondaryWorkoutStepTargetCapable", "BOOLEAN", "NULLABLE"),
            ("segmentCapable", "BOOLEAN", "NULLABLE"),
            ("segmentPointCapable", "BOOLEAN", "NULLABLE"),
            ("setBodyCompositionCapable", "BOOLEAN", "NULLABLE"),
            ("settingCapable", "BOOLEAN", "NULLABLE"),
            ("skipLastWorkoutStepInRepeatBlockCapable", "BOOLEAN", "NULLABLE"),
            ("sleepAlignmentCapable", "BOOLEAN", "NULLABLE"),
            ("sleepFitFileReceiveCapable", "BOOLEAN", "NULLABLE"),
            ("sleepNeedCapable", "BOOLEAN", "NULLABLE"),
            ("sleepScoreCapable", "BOOLEAN", "NULLABLE"),
            ("sleepSkinTemperatureCapable", "BOOLEAN", "NULLABLE"),
            ("sleepTimeCapable", "BOOLEAN", "NULLABLE"),
            ("smallFitFileOnlyCapable", "BOOLEAN", "NULLABLE"),
            ("solarPanelUtilizationCapable", "BOOLEAN", "NULLABLE"),
            ("spectatorMessagingCapable", "BOOLEAN", "NULLABLE"),
            ("sportCapable", "BOOLEAN", "NULLABLE"),
            ("sportingEventCapable", "BOOLEAN", "NULLABLE"),
            ("stairStepperOptionCapable", "BOOLEAN", "NULLABLE"),
            ("standaloneFirstbeatActivityProcessingCapable", "BOOLEAN", "NULLABLE"),
            ("stepsTrueUpChartCapable", "BOOLEAN", "NULLABLE"),
            ("strengthOptionsCapable", "BOOLEAN", "NULLABLE"),
            ("strengthTrainingPlanCapable", "BOOLEAN", "NULLABLE"),
            ("strengthWorkoutCapable", "BOOLEAN", "NULLABLE"),
            ("sweatLossCapable", "BOOLEAN", "NULLABLE"),
            ("swimAlgorithmCapable", "BOOLEAN", "NULLABLE"),
            ("swimmingHeartRateZoneCapable", "BOOLEAN", "NULLABLE"),
            ("swimWorkout2Capable", "BOOLEAN", "NULLABLE"),
            ("swimWorkoutCapable", "BOOLEAN", "NULLABLE"),
            ("syncActivityEditsCapable", "BOOLEAN", "NULLABLE"),
            ("topoactiveMapsRealTimeSettingCapable", "BOOLEAN", "NULLABLE"),
            ("trainableTriathlonEventCapable", "BOOLEAN", "NULLABLE"),
            ("trainingEffectLabelCapable", "BOOLEAN", "NULLABLE"),
            ("trainingLoadBalanceCapable", "BOOLEAN", "NULLABLE"),
            ("trainingPlanCapable", "BOOLEAN", "NULLABLE"),
            ("trainingReadinessCapable", "BOOLEAN", "NULLABLE"),
            ("trainingStatusCapable", "BOOLEAN", "NULLABLE"),
            ("trainingStatusPauseCapable", "BOOLEAN", "NULLABLE"),
            ("userProfileCapable", "BOOLEAN", "NULLABLE"),
            ("userTcxExportCapable", "BOOLEAN", "NULLABLE"),
            ("vbtCapable", "BOOLEAN", "NULLABLE"),
            ("vo2MaxBikeCapable", "BOOLEAN", "NULLABLE"),
            ("vo2MaxRunCapable", "BOOLEAN", "NULLABLE"),
            ("walkingSportsCapable", "BOOLEAN", "NULLABLE"),
            ("walkOptionCapable", "BOOLEAN", "NULLABLE"),
            ("walkWorkoutCapable", "BOOLEAN", "NULLABLE"),
            ("wearableBackupRestoreCapable", "BOOLEAN", "NULLABLE"),
            ("weatherAlertsCapable", "BOOLEAN", "NULLABLE"),
            ("weatherSettingsCapable", "BOOLEAN", "NULLABLE"),
            ("weightGoalCapable", "BOOLEAN", "NULLABLE"),
            ("wheelchairCapable", "BOOLEAN", "NULLABLE"),
            ("workoutAudioPromptsCapable", "BOOLEAN", "NULLABLE"),
            ("workoutCapable", "BOOLEAN", "NULLABLE"),
            ("xcSkiPowerZonesCapable", "BOOLEAN", "NULLABLE"),
            ("yogaCapable", "BOOLEAN", "NULLABLE"),
            ("yogaOptionCapable", "BOOLEAN", "NULLABLE"),
            ("yogaWorkoutCapable", "BOOLEAN", "NULLABLE"),
            ("defaultSettingsHbaseMigrated", "BOOLEAN", "NULLABLE"),
            ("bestInClassVideoLink", "STRING", "NULLABLE"),
            ("deviceVideoPageLink", "STRING", "NULLABLE"),
            ("deviceEmbedVideoLink", "STRING", "NULLABLE"),
            ("primaryApplication", "STRING", "NULLABLE"),
            ("minGCMAndroidVersion", "STRING", "NULLABLE"),
            ("minGCMiOSVersion", "STRING", "NULLABLE"),
            ("minGCMWindowsVersion", "STRING", "NULLABLE"),
            ("minGCMHarmonyVersion", "STRING", "NULLABLE"),
            ("minGolfAppAndroidVersion", "STRING", "NULLABLE"),
            ("minGolfAppiOSVersion", "STRING", "NULLABLE"),
            ("maxWorkoutCount", "INTEGER", "NULLABLE"),
            ("deviceCategories", "JSON", "NULLABLE"),
            ("deviceTags", "JSON", "NULLABLE"),
            ("incompatibleApplications", "JSON", "NULLABLE"),
            ("supportedHrZones", "JSON", "NULLABLE"),
            ("otherAssociation", "JSON", "NULLABLE"),
            ("primaryActivityTrackerIndicator", "JSON", "NULLABLE"),
            ("courseFileType", "JSON", "NULLABLE"),
            ("deviceSettingFileType", "JSON", "NULLABLE"),
            ("goalFileType", "JSON", "NULLABLE"),
            ("languageSettingFileType", "JSON", "NULLABLE"),
            ("personalRecordFileType", "JSON", "NULLABLE"),
            ("scheduleFileType", "JSON", "NULLABLE"),
            ("settingFileType", "JSON", "NULLABLE"),
            ("sportFileType", "JSON", "NULLABLE"),
            ("userProfileFileType", "JSON", "NULLABLE"),
            ("workoutFileType", "JSON", "NULLABLE"),
        ),
        source_pattern="devices.json",
        merge_files=False,
    ),
    "device_last_used": TableConfig(
        name="device_last_used",
        schema=_make_schema(
            ("userDeviceId", "INTEGER", "NULLABLE"),
            ("userProfileNumber", "INTEGER", "NULLABLE"),
            ("applicationNumber", "INTEGER", "NULLABLE"),
            ("lastUsedDeviceApplicationKey", "STRING", "NULLABLE"),
            ("lastUsedDeviceName", "STRING", "NULLABLE"),
            ("lastUsedDeviceUploadTime", "INTEGER", "NULLABLE"),
            ("imageUrl", "STRING", "NULLABLE"),
            ("released", "BOOLEAN", "NULLABLE"),
        ),
        source_pattern="device_last_used.json",
        merge_files=False,
    ),
    "gear": TableConfig(
        name="gear",
        schema=_make_schema(
            ("gearPk", "INTEGER", "REQUIRED"),
            ("uuid", "STRING", "NULLABLE"),
            ("userProfilePk", "INTEGER", "NULLABLE"),
            ("gearMakeName", "STRING", "NULLABLE"),
            ("gearModelName", "STRING", "NULLABLE"),
            ("gearTypeName", "STRING", "NULLABLE"),
            ("gearStatusName", "STRING", "NULLABLE"),
            ("displayName", "STRING", "NULLABLE"),
            ("customMakeModel", "STRING", "NULLABLE"),
            ("dateBegin", "STRING", "NULLABLE"),
            ("dateEnd", "STRING", "NULLABLE"),
            ("maximumMeters", "FLOAT", "NULLABLE"),
            ("notified", "BOOLEAN", "NULLABLE"),
            ("createDate", "STRING", "NULLABLE"),
            ("updateDate", "STRING", "NULLABLE"),
            ("imageNameLarge", "STRING", "NULLABLE"),
            ("imageNameMedium", "STRING", "NULLABLE"), 
            ("imageNameSmall", "STRING", "NULLABLE"),
        ),
        source_pattern="gear_list.json",
        merge_files=False,
    ),
    "health_stats": TableConfig(
        name="health_stats",
        schema=_make_schema(
            ("date", "DATE", "REQUIRED"),
            ("userProfileId", "INTEGER", "NULLABLE"),
            ("totalKilocalories", "FLOAT", "NULLABLE"),
            ("activeKilocalories", "FLOAT", "NULLABLE"),
            ("bmrKilocalories", "FLOAT", "NULLABLE"),
            ("wellnessKilocalories", "FLOAT", "NULLABLE"),
            ("burnedKilocalories", "FLOAT", "NULLABLE"),
            ("consumedKilocalories", "FLOAT", "NULLABLE"),
            ("remainingKilocalories", "FLOAT", "NULLABLE"),
            ("totalSteps", "INTEGER", "NULLABLE"),
            ("netCalorieGoal", "FLOAT", "NULLABLE"),
            ("totalDistanceMeters", "INTEGER", "NULLABLE"),
            ("wellnessDistanceMeters", "INTEGER", "NULLABLE"),
            ("wellnessActiveKilocalories", "FLOAT", "NULLABLE"),
            ("netRemainingKilocalories", "FLOAT", "NULLABLE"),
            ("userDailySummaryId", "INTEGER", "NULLABLE"),
            ("calendarDate", "STRING", "NULLABLE"),
            ("rule", "JSON", "NULLABLE"),
            ("uuid", "STRING", "NULLABLE"),
            ("dailyStepGoal", "INTEGER", "NULLABLE"),
            ("wellnessStartTimeGmt", "STRING", "NULLABLE"),
            ("wellnessStartTimeLocal", "STRING", "NULLABLE"),
            ("wellnessEndTimeGmt", "STRING", "NULLABLE"),
            ("wellnessEndTimeLocal", "STRING", "NULLABLE"),
            ("durationInMilliseconds", "INTEGER", "NULLABLE"),
            ("wellnessDescription", "STRING", "NULLABLE"),
            ("highlyActiveSeconds", "INTEGER", "NULLABLE"),
            ("activeSeconds", "INTEGER", "NULLABLE"),
            ("sedentarySeconds", "INTEGER", "NULLABLE"),
            ("sleepingSeconds", "INTEGER", "NULLABLE"),
            ("includesWellnessData", "BOOLEAN", "NULLABLE"),
            ("includesActivityData", "BOOLEAN", "NULLABLE"),
            ("includesCalorieConsumedData", "BOOLEAN", "NULLABLE"),
            ("privacyProtected", "BOOLEAN", "NULLABLE"),
            ("moderateIntensityMinutes", "INTEGER", "NULLABLE"),
            ("vigorousIntensityMinutes", "INTEGER", "NULLABLE"),
            ("floorsAscendedInMeters", "FLOAT", "NULLABLE"),
            ("floorsDescendedInMeters", "FLOAT", "NULLABLE"),
            ("floorsAscended", "FLOAT", "NULLABLE"),
            ("floorsDescended", "FLOAT", "NULLABLE"),
            ("intensityMinutesGoal", "INTEGER", "NULLABLE"),
            ("userFloorsAscendedGoal", "INTEGER", "NULLABLE"),
            ("minHeartRate", "INTEGER", "NULLABLE"),
            ("maxHeartRate", "INTEGER", "NULLABLE"),
            ("restingHeartRate", "INTEGER", "NULLABLE"),
            ("lastSevenDaysAvgRestingHeartRate", "INTEGER", "NULLABLE"),
            ("source", "STRING", "NULLABLE"),
            ("averageStressLevel", "INTEGER", "NULLABLE"),
            ("maxStressLevel", "INTEGER", "NULLABLE"),
            ("stressDuration", "INTEGER", "NULLABLE"),
            ("restStressDuration", "INTEGER", "NULLABLE"),
            ("activityStressDuration", "INTEGER", "NULLABLE"),
            ("uncategorizedStressDuration", "INTEGER", "NULLABLE"),
            ("totalStressDuration", "INTEGER", "NULLABLE"),
            ("lowStressDuration", "INTEGER", "NULLABLE"),
            ("mediumStressDuration", "INTEGER", "NULLABLE"),
            ("highStressDuration", "INTEGER", "NULLABLE"),
            ("stressPercentage", "FLOAT", "NULLABLE"),
            ("restStressPercentage", "FLOAT", "NULLABLE"),
            ("activityStressPercentage", "FLOAT", "NULLABLE"),
            ("uncategorizedStressPercentage", "FLOAT", "NULLABLE"),
            ("lowStressPercentage", "FLOAT", "NULLABLE"),
            ("mediumStressPercentage", "FLOAT", "NULLABLE"),
            ("highStressPercentage", "FLOAT", "NULLABLE"),
            ("stressQualifier", "STRING", "NULLABLE"),
            ("measurableAwakeDuration", "INTEGER", "NULLABLE"),
            ("measurableAsleepDuration", "INTEGER", "NULLABLE"),
            ("lastSyncTimestampGMT", "STRING", "NULLABLE"),
            ("minAvgHeartRate", "INTEGER", "NULLABLE"),
            ("maxAvgHeartRate", "INTEGER", "NULLABLE"),
            ("bodyBatteryChargedValue", "INTEGER", "NULLABLE"),
            ("bodyBatteryDrainedValue", "INTEGER", "NULLABLE"),
            ("bodyBatteryHighestValue", "INTEGER", "NULLABLE"),
            ("bodyBatteryLowestValue", "INTEGER", "NULLABLE"),
            ("bodyBatteryMostRecentValue", "INTEGER", "NULLABLE"),
            ("bodyBatteryDuringSleep", "INTEGER", "NULLABLE"),
            ("bodyBatteryAtWakeTime", "INTEGER", "NULLABLE"),
            ("bodyBatteryVersion", "FLOAT", "NULLABLE"),
            ("bodyBatteryActivityEventList", "JSON", "NULLABLE"),
            ("bodyBatteryDynamicFeedbackEvent", "JSON", "NULLABLE"),
            ("endOfDayBodyBatteryDynamicFeedbackEvent", "JSON", "NULLABLE"),
            ("abnormalHeartRateAlertsCount", "INTEGER", "NULLABLE"),
            ("averageSpo2", "FLOAT", "NULLABLE"),
            ("lowestSpo2", "FLOAT", "NULLABLE"),
            ("latestSpo2", "FLOAT", "NULLABLE"),
            ("latestSpo2ReadingTimeGmt", "STRING", "NULLABLE"),
            ("latestSpo2ReadingTimeLocal", "STRING", "NULLABLE"),
            ("averageMonitoringEnvironmentAltitude", "FLOAT", "NULLABLE"),
            ("restingCaloriesFromActivity", "FLOAT", "NULLABLE"),
            ("avgWakingRespirationValue", "FLOAT", "NULLABLE"),
            ("highestRespirationValue", "FLOAT", "NULLABLE"),
            ("lowestRespirationValue", "FLOAT", "NULLABLE"),
            ("latestRespirationValue", "FLOAT", "NULLABLE"),
            ("latestRespirationTimeGMT", "STRING", "NULLABLE"),
            ("respirationAlgorithmVersion", "INTEGER", "NULLABLE"),
        ),
        source_pattern="health_*.json",
        merge_files=False,
    ),
    "health_heart_rate": TableConfig(
        name="health_heart_rate",
        schema=_make_schema(
            ("date", "DATE", "REQUIRED"),
            ("userProfilePK", "INTEGER", "NULLABLE"),
            ("calendarDate", "STRING", "NULLABLE"),
            ("startTimestampGMT", "STRING", "NULLABLE"),
            ("endTimestampGMT", "STRING", "NULLABLE"),
            ("startTimestampLocal", "STRING", "NULLABLE"),
            ("endTimestampLocal", "STRING", "NULLABLE"),
            ("maxHeartRate", "INTEGER", "NULLABLE"),
            ("minHeartRate", "INTEGER", "NULLABLE"),
            ("restingHeartRate", "INTEGER", "NULLABLE"),
            ("lastSevenDaysAvgRestingHeartRate", "INTEGER", "NULLABLE"),
            ("heartRateValues", "JSON", "NULLABLE"),
            ("heartRateValueDescriptors", "JSON", "NULLABLE"),
        ),
        source_pattern="health_*.json",
        merge_files=False,
    ),
    "health_body_composition": TableConfig(
        name="health_body_composition",
        schema=_make_schema(
            ("date", "DATE", "REQUIRED"),
            ("startDate", "STRING", "NULLABLE"),
            ("endDate", "STRING", "NULLABLE"),
            ("weight", "FLOAT", "NULLABLE"),
            ("bmi", "FLOAT", "NULLABLE"),
            ("bodyFat", "FLOAT", "NULLABLE"),
            ("bodyWater", "FLOAT", "NULLABLE"),
            ("boneMass", "FLOAT", "NULLABLE"),
            ("muscleMass", "FLOAT", "NULLABLE"),
            ("physiqueRating", "INTEGER", "NULLABLE"),
            ("visceralFat", "INTEGER", "NULLABLE"),
            ("metabolicAge", "INTEGER", "NULLABLE"),
        ),
        source_pattern="health_*.json",
        merge_files=False,
    ),
    "profile": TableConfig(
        name="profile",
        schema=_make_schema(
            ("id", "INTEGER", "REQUIRED"),
            ("userData", "JSON", "NULLABLE"),
            ("userSleep", "JSON", "NULLABLE"),
            ("connectDate", "STRING", "NULLABLE"),
            ("sourceType", "STRING", "NULLABLE"),
            ("userSleepWindows", "JSON", "NULLABLE"),
        ),
        source_pattern="profile.json",
        merge_files=False,
    ),
    "unit_system": TableConfig(
        name="unit_system",
        schema=_make_schema(
            ("value", "STRING", "REQUIRED"),
        ),
        source_pattern="unit_system.json",
        merge_files=False,
    ),
    "user_info": TableConfig(
        name="user_info",
        schema=_make_schema(
            ("full_name", "STRING", "NULLABLE"),
        ),
        source_pattern="user_info.json",
        merge_files=False,
    ),
}

# Provider to schema mapping
PROVIDER_SCHEMAS: dict[str, dict[str, TableConfig]] = {
    "garmin": GARMIN_SCHEMAS,
}